### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kurtommy** [MattMcFarland/TitaniumAlloy-FontAwesome-Example#1]
![schermata 2014-05-21 alle 10 15 23](https://cloud.githubusercontent.com/assets/2192625/3037501/22f7807a-e0c0-11e3-9002-5245e5c8b5d4.png)

**Comment by MattMcFarland** [comment]
Hi,

Sorry to see that it is not working, and thanks for sharing!  Off the top of my head, I'm not sure what the issue is.  Can you share with me the version of alloy you are using, version of titanium sdk, and what you are building on?  (android? ios? mobileweb?) 

I'm also wondering if you could try a Build...clean.. I had a simliar issue to this and it fixed the problem.  

Other than that, since I cannot duplicate the problem, don't know where to start!

**Comment by daveeel** [comment]
Ah, I just reported the same issue before reading your latest comment. 
Yes, by deleting the build folders and rebuild does solve the issue. Great!
